/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles_rotativos;

import clases.*;
import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;

import java.io.Writer;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateo
 */
public class Cargar extends javax.swing.JPanel {

    public static String marca1;
    public static String nrochasis1;

    int filas_ventas;

    /**
     * Creates new form Cargar
     */
    public Cargar() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nro_chasis_c = new javax.swing.JTextField();
        nro_motor_c = new javax.swing.JTextField();
        modelo_c = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        anio_c = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        enviar_btn1 = new javax.swing.JLabel();
        color_c = new javax.swing.JComboBox<>();
        tpo_cabina_c = new javax.swing.JComboBox<>();
        traccion_c = new javax.swing.JComboBox<>();
        marca_c = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nro_chasis = new javax.swing.JTextField();
        nro_motor = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        anio = new javax.swing.JTextField();
        enviar_btn = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        color = new javax.swing.JComboBox<>();
        cdad_puertas = new javax.swing.JComboBox<>();
        marca = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        enviar_btn2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        dni_v = new javax.swing.JTextField();
        telefono_v = new javax.swing.JTextField();
        nombre_v = new javax.swing.JTextField();
        apellido_v = new javax.swing.JTextField();
        correo_v = new javax.swing.JTextField();
        nro_contrato = new javax.swing.JTextField();
        monto_v = new javax.swing.JTextField();
        fecha_v = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cuil_v = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        tipo_moneda_v = new javax.swing.JComboBox<>();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jLabel8.setText("Tipo de cabina");

        jLabel9.setText("Numero de chasis:");

        jLabel10.setText("Numero de motor:");

        jLabel11.setText("Color:");

        jLabel12.setText("Marca:");

        jLabel13.setText("Modelo:");

        jLabel14.setText("Traccion:");

        nro_motor_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nro_motor_cActionPerformed(evt);
            }
        });

        jLabel15.setText("Año:");

        jLabel28.setText(null);

        enviar_btn1.setText(" Enviar ");
        enviar_btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enviar_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enviar_btn1MousePressed(evt);
            }
        });

        color_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "azul", "verde", "blanco", "negro" }));

        tpo_cabina_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "simple", "doble" }));

        traccion_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "delantera", "trasera", "4x4" }));

        marca_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ford", "volskwagen", "fiat", "peugeot" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                                .addComponent(nro_motor_c, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modelo_c, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(anio_c, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(color_c, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(traccion_c, 0, 120, Short.MAX_VALUE)
                                    .addComponent(marca_c, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nro_chasis_c, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(tpo_cabina_c, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enviar_btn1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(72, 72, 72)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tpo_cabina_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nro_chasis_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nro_motor_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(color_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(marca_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(modelo_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(traccion_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anio_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviar_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 204, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 250, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CAMIONETAS", jPanel1);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel1.setText("Cantidad de puertas:");

        jLabel2.setText("Numero de chasis:");

        jLabel3.setText("Numero de motor:");

        jLabel4.setText("Color:");

        jLabel5.setText("Marca:");

        jLabel6.setText("Modelo:");

        jLabel7.setText("Año:");

        nro_chasis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nro_chasisMousePressed(evt);
            }
        });

        nro_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nro_motorActionPerformed(evt);
            }
        });

        enviar_btn.setText(" Enviar ");
        enviar_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enviar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enviar_btnMousePressed(evt);
            }
        });

        jLabel30.setText(null);

        color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "blanco", "azul", "verde", "negro" }));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        cdad_puertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5" }));

        marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ford", "volskwagen", "fiat", "peugeot" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(nro_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enviar_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addComponent(modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(anio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nro_chasis, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(cdad_puertas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cdad_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nro_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nro_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(enviar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AUTOS", jPanel2);

        jLabel17.setText("DNI:");

        jLabel18.setText("Telefono:");

        jLabel19.setText("Nombre:");

        jLabel20.setText("Apellido:");

        jLabel21.setText("Correo electronico:");

        jLabel22.setText("Numero de contrato:");

        jLabel23.setText("Monto:");

        enviar_btn2.setText("Cargar");
        enviar_btn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enviar_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enviar_btn2MousePressed(evt);
            }
        });

        jLabel24.setText("Fecha:");

        jLabel16.setText("Tipo de moneda:");

        jLabel25.setText("CLIENTE");

        jLabel26.setText("VENTA");

        jLabel29.setText("CUIL:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehiculo", "Modelo", "Marca", "Color", "Nro de chasis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel31.setText(null);

        tipo_moneda_v.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARG", "USD", "BTC" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enviar_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(85, 680, Short.MAX_VALUE)
                                .addComponent(jLabel31)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dni_v, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(telefono_v)
                                            .addComponent(nombre_v)
                                            .addComponent(apellido_v)
                                            .addComponent(correo_v)
                                            .addComponent(cuil_v)))
                                    .addComponent(jLabel26)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nro_contrato, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(monto_v)
                                            .addComponent(fecha_v)
                                            .addComponent(tipo_moneda_v, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dni_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefono_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correo_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuil_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(nro_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(monto_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(fecha_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tipo_moneda_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(enviar_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("VENTA", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nro_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nro_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nro_motorActionPerformed


    private void enviar_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_btnMousePressed
        for (int i = 0; i < Vehiculo.vehiculo.size(); i++) {
            if(Vehiculo.vehiculo.get(i).getNro_chasis() == Integer.parseInt(nro_chasis.getText())){
                  Component jFrame = null;
                JOptionPane.showMessageDialog(jFrame,"Error, ya existe un vehiculo con ese numero de chasis");
                break;
            }
            else{
                  CargadeAutosInterfaz();
                  break;
            }
        }
      
        TablaVentas();


    }//GEN-LAST:event_enviar_btnMousePressed


    private void nro_motor_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nro_motor_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nro_motor_cActionPerformed

    private void enviar_btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_btn1MousePressed

        CargadeCamionetasInterfaz();
        TablaVentas();

    }//GEN-LAST:event_enviar_btn1MousePressed

    private void CargadeAutosInterfaz() {

        File autos = new File("autos.txt");
        try {

            FileWriter autosr = new FileWriter(autos, true);
            BufferedWriter autosb = new BufferedWriter(autosr);

            autosb.write("\n");

            autosb.write(nro_chasis.getText() + " " + nro_motor.getText() + " " + marca.getSelectedItem().toString() + " " + color.getSelectedItem().toString() + " " + modelo.getText() + " " + anio.getText() + " " + cdad_puertas.getSelectedItem().toString());
            //  System.out.println(nro_chasis.getText());
            Vehiculo auto = new Auto(Integer.parseInt(nro_chasis.getText()), Integer.parseInt(nro_motor.getText()), color.getSelectedItem().toString(), marca.getSelectedItem().toString(), modelo.getText(), anio.getText(), Integer.parseInt(cdad_puertas.getSelectedItem().toString()));

            Vehiculo.vehiculo.add(auto);

            autosb.close();

            nro_chasis.setText(null);
            nro_motor.setText(null);

            modelo.setText(null);
            anio.setText(null);
            jLabel30.setText("Enviado con exito.");

        } catch (IOException ex) {
            Logger.getLogger(Cargar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.lang.NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error, complete todas las casillas.", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }

    public void actualizarlista(int tipo) throws FileNotFoundException, IOException {
        if (tipo == 1) {

            int n = Integer.parseInt(nrochasis1);

            for (int i = 0; i < Vehiculo.vehiculo.size(); i++) {

                if (Vehiculo.vehiculo.get(i).getNro_chasis() == n) {

                    Vehiculo.vehiculo.remove(Vehiculo.vehiculo.get(i));

                    for (int j = 0; j < Vehiculo.vehiculo.size(); j++) {
                        System.out.println(Vehiculo.vehiculo.get(j));
                    }

                }
            }

            File file = new File("autos.txt");
            if (file.exists()) {
                PrintWriter autoosr = new PrintWriter(file);
                autoosr.close();
            }

            FileWriter autsr = new FileWriter(file, true);
            BufferedWriter autsb = new BufferedWriter(autsr);

            autsb.write("nro_chasis nro_motor marca color modelo anio cant_puertas");

            for (int j = 0; j < Vehiculo.vehiculo.size(); j++) {
                
                

                if (Vehiculo.vehiculo.get(j) instanceof Auto) {

                    Auto cc = (Auto) Vehiculo.vehiculo.get(j);
                    autsb.write("\n");
                    autsb.write(Vehiculo.vehiculo.get(j).getNro_chasis() + " " + Vehiculo.vehiculo.get(j).getNro_motor() + " " + Vehiculo.vehiculo.get(j).getMarca() + " " + Vehiculo.vehiculo.get(j).getColor() + " " + Vehiculo.vehiculo.get(j).getModelo() + " " + Vehiculo.vehiculo.get(j).getAnio() + " " + cc.getCant_puertas());

                }
            }
            autsb.close();
            autsr.close();

        } else {
            int n = Integer.parseInt(nrochasis1);

            for (int i = 0; i < Vehiculo.vehiculo.size(); i++) {

                if (Vehiculo.vehiculo.get(i).getNro_chasis() == n) {

                    Vehiculo.vehiculo.remove(Vehiculo.vehiculo.get(i));

                    /*for (int j = 0 ; j < Vehiculo.vehiculo.size(); j++){
                        System.out.println(Vehiculo.vehiculo.get(j));
                    } 
                     */
                }
            }
            File file = new File("camionetas.txt");
            if (file.exists()) {
                PrintWriter autoosr = new PrintWriter(file);
                autoosr.close();
            }

            FileWriter autsr = new FileWriter(file, true);
            BufferedWriter autsb = new BufferedWriter(autsr);

            autsb.write("nro_chasis nro_motor color marca modelo anio traccion tpo_cabina");

            for (int j = 0; j < Vehiculo.vehiculo.size(); j++) {

                if (Vehiculo.vehiculo.get(j) instanceof Camioneta) {

                    Camioneta cc = (Camioneta) Vehiculo.vehiculo.get(j);
                    autsb.write("\n");
                    autsb.write(Vehiculo.vehiculo.get(j).getNro_chasis() + " " + Vehiculo.vehiculo.get(j).getNro_motor() + " " + Vehiculo.vehiculo.get(j).getColor() + " " + Vehiculo.vehiculo.get(j).getMarca() + " " + Vehiculo.vehiculo.get(j).getModelo() + " " + Vehiculo.vehiculo.get(j).getAnio() + " " + cc.getTraccion() + " " + cc.getTpo_cabina());

                }
            }
            autsb.close();
            autsr.close();

        }

    }

    private void CargadeCamionetasInterfaz() {

        File camionetas = new File("camionetas.txt");

        try {

            FileWriter camionetasr = new FileWriter(camionetas, true);
            BufferedWriter camionetasb = new BufferedWriter(camionetasr);

            camionetasb.write("\n");

            camionetasb.write(nro_chasis_c.getText() + " " + nro_motor_c.getText() + " " + color_c.getSelectedItem().toString() + " " + marca_c.getSelectedItem().toString() + " " + modelo_c.getText() + " " + anio_c.getText() + " " + traccion_c.getSelectedItem().toString() + " " + tpo_cabina_c.getSelectedItem().toString());

            //cb.getTraccion(), numero_chasis, numero_motor, cb.getColor(), cb.getMarca(), cb.getModelo(), cb.getAnio(), cb.getTpo_cabina()
            //
            Vehiculo camioneta = new Camioneta(Integer.parseInt(nro_chasis_c.getText()), Integer.parseInt(nro_motor_c.getText()), color_c.getSelectedItem().toString(), marca_c.getSelectedItem().toString(), modelo_c.getText(), anio_c.getText(), traccion_c.getSelectedItem().toString(), tpo_cabina_c.getSelectedItem().toString());

            Vehiculo.vehiculo.add(camioneta);

            camionetasb.close();

            nro_chasis_c.setText(null);
            nro_motor_c.setText(null);

            modelo_c.setText(null);
            anio_c.setText(null);

            jLabel28.setText("Enviado con exito.");
        } catch (IOException ex) {
            Logger.getLogger(Cargar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.lang.NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error, complete todas las casillas.", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void CargadeVentasInterfaz() {
        
        File camionetas = new File("ventas.txt");

        try {

            FileWriter ventas = new FileWriter(camionetas, true);
            BufferedWriter ventasb = new BufferedWriter(ventas);

            ventasb.write("\n");
            nrochasis1 = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
            marca1 = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();

            ventasb.write(dni_v.getText() + " " + telefono_v.getText() + " " + cuil_v.getText() + " " + nombre_v.getText() + " " + apellido_v.getText() + " " + correo_v.getText() + " " + nro_contrato.getText() + " " + monto_v.getText() + " " + fecha_v.getText() + " " + tipo_moneda_v.getSelectedItem().toString() + " " + marca1 + " " + nrochasis1);

            Comprador comprador = new Comprador(Long.parseLong(dni_v.getText()), Long.parseLong(telefono_v.getText()), Long.parseLong(cuil_v.getText()), nombre_v.getText(), apellido_v.getText(), correo_v.getText());

            Ventas venta = new Ventas(Integer.parseInt(nro_contrato.getText()), Float.parseFloat(monto_v.getText()), fecha_v.getText(), tipo_moneda_v.getSelectedItem().toString(), marca1, nrochasis1, comprador);

            for (int i = 0; i < Vehiculo.vehiculo.size(); i++) {
                if (Vehiculo.vehiculo.get(i).getNro_chasis() == Integer.parseInt(nrochasis1)) {
                    if (Vehiculo.vehiculo.get(i) instanceof Auto) {
                        //         Tablas.filas_autos--;
                        actualizarlista(1);
                    } else {
                        //         Tablas.filas_camionetas--;
                        actualizarlista(0);
                    }

                }

            }

            Ventas.ventas.add(venta);

            ventasb.close();
            ventas.close();

            dni_v.setText(null);
            telefono_v.setText(null);
            cuil_v.setText(null);
            nombre_v.setText(null);
            apellido_v.setText(null);
            correo_v.setText(null);
            nro_contrato.setText(null);
            monto_v.setText(null);
            fecha_v.setText(null);

            jLabel31.setText("Enviado con exito.");

        } catch (IOException ex) {
            Logger.getLogger(Cargar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.lang.NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error, Ingreso una palabra donde se esperaba un numero.", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error, complete todas las casillas.", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void enviar_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_btn2MousePressed

        CargadeVentasInterfaz();

        TablaVentas();
        //     filas_ventas--;

    }//GEN-LAST:event_enviar_btn2MousePressed

    public void TablaVentas() {

        DefaultTableModel modelo = new DefaultTableModel();

        ArrayList<Object> nombrecolumna = new ArrayList<Object>();
        nombrecolumna.add("Vehiculo");
        nombrecolumna.add("Modelo");
        nombrecolumna.add("Marca");
        nombrecolumna.add("Color");
        nombrecolumna.add("Nro de chasis");
        for (Object columna : nombrecolumna) {
            modelo.addColumn(columna);
        }

        this.jTable1.setModel(modelo);

        for (int k = 0; k < Vehiculo.vehiculo.size(); k++) {
            if (Vehiculo.vehiculo.get(k) instanceof Auto) {
                Auto cc = (Auto) Vehiculo.vehiculo.get(k);

                String numero_chasis = Integer.toString(cc.getNro_chasis());

                String tab[] = {"Auto", cc.getModelo(), cc.getMarca(), cc.getColor(), numero_chasis};

                modelo.addRow(tab);
            } else {
                Camioneta cc = (Camioneta) Vehiculo.vehiculo.get(k);
                String numero_chasis = Integer.toString(cc.getNro_chasis());

                String tab2[] = {"Camioneta", cc.getModelo(), cc.getMarca(), cc.getColor(), numero_chasis};
                modelo.addRow(tab2);
            }

        }

        jTable1.setModel(modelo);

    }
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered

        TablaVentas();

    }//GEN-LAST:event_jPanel3MouseEntered

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        jLabel28.setText(null);
        jLabel30.setText(null);


    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void nro_chasisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nro_chasisMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nro_chasisMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anio;
    private javax.swing.JTextField anio_c;
    private javax.swing.JTextField apellido_v;
    private javax.swing.JComboBox<String> cdad_puertas;
    private javax.swing.JComboBox<String> color;
    private javax.swing.JComboBox<String> color_c;
    private javax.swing.JTextField correo_v;
    private javax.swing.JTextField cuil_v;
    private javax.swing.JTextField dni_v;
    private javax.swing.JLabel enviar_btn;
    private javax.swing.JLabel enviar_btn1;
    private javax.swing.JLabel enviar_btn2;
    private javax.swing.JTextField fecha_v;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> marca;
    private javax.swing.JComboBox<String> marca_c;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField modelo_c;
    private javax.swing.JTextField monto_v;
    private javax.swing.JTextField nombre_v;
    private javax.swing.JTextField nro_chasis;
    private javax.swing.JTextField nro_chasis_c;
    private javax.swing.JTextField nro_contrato;
    private javax.swing.JTextField nro_motor;
    private javax.swing.JTextField nro_motor_c;
    private javax.swing.JTextField telefono_v;
    private javax.swing.JComboBox<String> tipo_moneda_v;
    private javax.swing.JComboBox<String> tpo_cabina_c;
    private javax.swing.JComboBox<String> traccion_c;
    // End of variables declaration//GEN-END:variables
}
